//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_Material
    {
        public int idMaterial { get; set; }
        public int idProduct { get; set; }
        public int Procent { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Products Products { get; set; }
    }
}
