//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Prod_Material = new HashSet<Prod_Material>();
        }
    
        public int idProducts { get; set; }
        public string ProdName { get; set; }
        public int Artocle { get; set; }
        public int MinCostForAgent { get; set; }
        public string Image { get; set; }
        public int IdTypeProd { get; set; }
        public int CountPresins { get; set; }
        public string NumberCeh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prod_Material> Prod_Material { get; set; }
        public virtual TypeProd TypeProd { get; set; }
    }
}
